# Generated by Django 4.2.6 on 2024-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Blouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Makeups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sanitaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sunglasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('sizes', models.CharField(max_length=300, verbose_name='Sizes:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
