# Generated by Django 4.2.6 on 2023-10-05 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price:'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=200, verbose_name='Zip Code'),
        ),
    ]
