# Generated by Django 4.2.6 on 2023-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_shippingaddress_date_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Nigeria', max_length=200, verbose_name='Country'),
        ),
    ]
